KCL-6914 Plus button click handler
Kentico/kontent-smart-link pull request #36
Opened 2021-04-27 08:17 UTC by vladislavb-kentico

- Implement initial iframe message for plus button
- Implement action iframe message for plus button
- Implement additional popover logic for plus button
- Refactored SDK configuration structure
- Implement custom Logger

2021-04-27 13:05 UTC, PeterSkoda requested changes
Some comments, otherwise good job!

2021-04-27 13:53 UTC, ChristopherJennings commented on src/lib/IFrameCommunicatorTypes.ts
> +export enum PlusButtonPermissionOption {
Is this a Permission status maybe?

2021-04-28 08:48 UTC, vladislavb-kentico commented on src/lib/NodeSmartLinkProvider.ts
> +      if (isInsideIFrame()) {
You are right, iframeCommunicator check if not necessary on l.261.

2021-04-28 10:25 UTC, vladislavb-kentico commented on src/lib/IFrameCommunicatorTypes.ts
> +export enum PlusButtonPermissionOption {
I decided to use `PlusButtonPermissionCheckResult` here because we already use it on the backend.

2021-04-28 10:46 UTC, PeterSkoda approved these changes

2021-05-03 06:07 UTC, merged